"""create tables

Revision ID: 3f4edf20feb3
Revises: 
Create Date: 2024-12-29 09:30:55.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4edf20feb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dividend_per_share', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ex_dividend_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dividend_info')
    op.drop_table('financial_statements')
    op.drop_table('stocks')
    # ### end Alembic commands ###